encoder_kwargs:
  rna:
    dims: [1024, 512, 150]
    norm: True
    norm_type: batch_norm
    dropout: False 
    dropout_p: 0.0
  atac:
    dims: [2048, 1024, 200]
    norm: True
    norm_type: batch_norm
    dropout: False 
    dropout_p: 0.0    
learning_rate: 0.001
weight_decay: 0.0001
covariate_specific_theta: False 
multimodal: True
is_binarized: True
encoder_multimodal_joint_layers: null