dataset_path: /stor/lep/data/pbmc10k_multiome/cfgen/pbmc10k_multiome_all_2500gene_006atac.h5mu #/stor/lep/data/pbmc10k_multiome/cfgen/pbmc10k_multiome_all.h5mu
valid_path: null #/stor/lep/data/pbmc10k_multiome/cfgen/pbmc10k_multiome_test.h5mu
layer_key: X_counts
covariate_keys: [cell_type]
conditioning_covariate: cell_type
theta_covariate: cell_type
subsample_frac: 1
one_hot_encode_features: False
split_rates: [0.8, 0.2]
cov_embedding_dimensions: 100
multimodal: True
is_binarized: True 