dataset_path: /stor/lep/diffusion/multiome/openproblem_filtered.h5mu
valid_path: null
layer_key: X_counts
covariate_keys: [cell_type]
conditioning_covariate: cell_type
theta_covariate: cell_type
subsample_frac: 1
one_hot_encode_features: False
split_rates: [0.90, 0.10]
cov_embedding_dimensions: 100
multimodal: True
is_binarized: True 